# Generated by Django 5.2.4 on 2025-07-16 13:57

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to=courses.models.handle_upload)),
                ('access', models.CharField(choices=[('anyone', 'Anyone'), ('email_required', 'Email_Required')], default='email_required', max_length=100)),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('soon', 'Coming Soon'), ('draft', 'DRAFT')], default='draft', max_length=20)),
            ],
        ),
    ]
